---
# Source: prometheus-operator/templates/exporters/node-exporter/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-node-exporter
  namespace: monitoring
  labels:
    app: prometheus-operator-node-exporter
    
    chart: prometheus-operator-8.8.0
    release: "prometheus-operator"
    heritage: "Tiller"
spec:
  jobLabel: jobLabel
  selector:
    matchLabels:
      app: prometheus-node-exporter
      release: prometheus-operator
  endpoints:
  - port: metrics
