---
# Source: prometheus-operator/charts/grafana/templates/clusterrolebinding.yaml

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-operator-grafana-clusterrolebinding
  labels:
    app: grafana
    chart: grafana-4.3.2
    release: prometheus-operator
    heritage: Tiller
subjects:
  - kind: ServiceAccount
    name: prometheus-operator-grafana
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: prometheus-operator-grafana-clusterrole
  apiGroup: rbac.authorization.k8s.io