---
# Source: prometheus-operator/charts/grafana/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: prometheus-operator-grafana
  namespace: monitoring
  labels:
    app: grafana
    chart: grafana-4.3.2
    heritage: Tiller
    release: prometheus-operator
rules:
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [prometheus-operator-grafana]
