version: '3'

services:

  pyapp:
    build:
      context: ./app
    image: briandavis/pyapp:latest
    ports:
      - "8000:8000"
    networks:
      default:

  unittests:
    build:
      context: ./app
    image:  briandavis/pyapp:latest
    command: [ "pytest", "/app/tests.py" ]