---
# Source: prometheus-operator/templates/alertmanager/alertmanager.yaml

apiVersion: monitoring.coreos.com/v1
kind: Alertmanager
metadata:
  name: prometheus-operator-alertmanager
  namespace: monitoring
  labels:
    app: prometheus-operator-alertmanager
    
    chart: prometheus-operator-8.8.0
    release: "prometheus-operator"
    heritage: "Tiller"
spec:
  baseImage: quay.io/prometheus/alertmanager
  version: v0.20.0
  replicas: 1
  listenLocal: false
  serviceAccountName: prometheus-operator-alertmanager
  externalUrl: http://prometheus-operator-alertmanager.monitoring:9093
  paused: false
  logFormat: "logfmt"
  logLevel:  "info"
  retention: "120h"
  routePrefix: "/"
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    
  portName: web
