---
# Source: prometheus-operator/templates/alertmanager/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus-operator-alertmanager
  namespace: monitoring
  labels:
    app: prometheus-operator-alertmanager
    
    chart: prometheus-operator-8.8.0
    release: "prometheus-operator"
    heritage: "Tiller"
imagePullSecrets:
  []
  
