---
# Source: prometheus-operator/templates/prometheus-operator/admission-webhooks/job-patch/job-createSecret.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name:  prometheus-operator-admission-create
  namespace: monitoring
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    app: prometheus-operator-admission-create    
    chart: prometheus-operator-8.8.0
    release: "prometheus-operator"
    heritage: "Tiller"
spec:
  template:
    metadata:
      name:  prometheus-operator-admission-create
      labels:
        app: prometheus-operator-admission-create        
        chart: prometheus-operator-8.8.0
        release: "prometheus-operator"
        heritage: "Tiller"
    spec:
      containers:
        - name: create
          image: jettech/kube-webhook-certgen:v1.0.0
          imagePullPolicy: 
          args:
            - create
            - --host=prometheus-operator-operator,prometheus-operator-operator.monitoring.svc
            - --namespace=monitoring
            - --secret-name=prometheus-operator-admission
          resources:
            {}
            
      restartPolicy: OnFailure
      serviceAccountName: prometheus-operator-admission
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
