{
 "title": "HTTP Status",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Response Time Merged",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sample_external_url_response_ms",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "200 Current Response Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 8 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sample_external_url_response_ms{url=\"https://httpstat.us/200\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "503 Current Response Time",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 8 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "sample_external_url_response_ms{url=\"https://httpstat.us/503\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "200 Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "sample_external_url_response_ms{url=\"https://httpstat.us/200\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "503 Response Time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ms", "label": "Latency (ms)" }
   ],
   "targets": [
    {
     "expr": "sample_external_url_response_ms{url=\"https://httpstat.us/503\"}",
     "legendFormat": "{{url}}"
    }
   ]
  },
  {
   "title": "503 Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sample_external_url_up{url=\"https://httpstat.us/200\"}"
    }
   ]
  },
  {
   "title": "503 Status",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sample_external_url_up{url=\"https://httpstat.us/503\"}"
    }
   ]
  }
 ]
}