---
# Source: prometheus-operator/charts/prometheus-node-exporter/templates/psp-clusterrole.yaml

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp-prometheus-operator-prometheus-node-exporter
  labels:     
    app: prometheus-node-exporter
    heritage: Tiller
    release: prometheus-operator
    chart: prometheus-node-exporter-1.8.2
    jobLabel: node-exporter
    
rules:
- apiGroups: ['extensions']
  resources: ['podsecuritypolicies']
  verbs:     ['use']
  resourceNames:
  - prometheus-operator-prometheus-node-exporter
