---
# Source: prometheus-operator/templates/grafana/configmaps-datasources.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-operator-grafana-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
    app: prometheus-operator-grafana
    
    chart: prometheus-operator-8.8.0
    release: "prometheus-operator"
    heritage: "Tiller"
data:
  datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://prometheus-operator-prometheus:9090/
      access: proxy
      isDefault: true
