---
# Source: prometheus-operator/templates/grafana/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-grafana
  namespace: monitoring
  labels:
    app: prometheus-operator-grafana
    
    chart: prometheus-operator-8.8.0
    release: "prometheus-operator"
    heritage: "Tiller"
spec:
  selector:
    matchLabels:
      app: grafana
      release: "prometheus-operator"
  namespaceSelector:
    matchNames:
      - "monitoring"
  endpoints:
  - port: service
    path: "/metrics"
