---
# Source: prometheus-operator/templates/prometheus-operator/servicemonitor.yaml

apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator-operator
  namespace: monitoring
  labels:
    app: prometheus-operator-operator
    
    chart: prometheus-operator-8.8.0
    release: "prometheus-operator"
    heritage: "Tiller"
spec:
  endpoints:
  - port: http
    honorLabels: true
  selector:
    matchLabels:
      app: prometheus-operator-operator
      release: "prometheus-operator"
  namespaceSelector:
    matchNames:
      - "monitoring"
