---
# Source: prometheus-operator/templates/prometheus/prometheus.yaml

apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus-operator-prometheus
  namespace: monitoring
  labels:
    app: prometheus-operator-prometheus
    
    chart: prometheus-operator-8.8.0
    release: "prometheus-operator"
    heritage: "Tiller"
spec:
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: prometheus-operator-alertmanager
        port: web
        pathPrefix: "/"
        apiVersion: v2
  baseImage: quay.io/prometheus/prometheus
  version: v2.15.2
  externalUrl: "http://prometheus.localtest.me/"
  paused: false
  replicas: 1
  logLevel:  info
  logFormat:  logfmt
  listenLocal: false
  enableAdminAPI: false
  retention: "10d"
  routePrefix: "/"
  serviceAccountName: prometheus-operator-prometheus
  serviceMonitorSelector:
    matchLabels:
      release: "prometheus-operator"

  serviceMonitorNamespaceSelector: {}
  podMonitorSelector:
    matchLabels:
      release: "prometheus-operator"

  podMonitorNamespaceSelector: {}
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
    
  ruleNamespaceSelector: {}
  ruleSelector:
    matchLabels:
      app: prometheus-operator
      release: "prometheus-operator"

  portName: web
