---
# Source: prometheus-operator/templates/prometheus/psp-clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-operator-prometheus-psp
  labels:
    app: prometheus-operator-prometheus
    
    chart: prometheus-operator-8.8.0
    release: "prometheus-operator"
    heritage: "Tiller"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-operator-prometheus-psp
subjects:
  - kind: ServiceAccount
    name: prometheus-operator-prometheus
    namespace: monitoring

